/**
 * Main Sitemap Index
 * 
 * This file is kept minimal - the actual sitemap.xml is generated as a static file
 * in /public by running: npm run generate-sitemaps
 * 
 * Next.js will serve the static sitemap.xml from /public automatically.
 * This file is here to satisfy Next.js routing requirements.
 */

import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  // Return empty array - actual sitemap is served from /public/sitemap.xml
  // The static file is generated by running: npm run generate-sitemaps
  return [];
}
