import { WooCommerceBrand } from "./types";

export const CATEGORY_BRANDS: Record<string, WooCommerceBrand[]> = {
  "apple-products": [
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
  ],
  "components": [
    { id: 515, name: "1st", slug: "1st", count: 1 },
    { id: 684, name: "1st Player", slug: "1st-player", count: 1 },
    { id: 2002, name: "A4Tech", slug: "a4tech", count: 1 },
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 681, name: "AeroCool", slug: "aerocool", count: 1 },
    { id: 982, name: "Aigo", slug: "aigo", count: 1 },
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 641, name: "AMD", slug: "amd", count: 1 },
    { id: 1141, name: "Antec", slug: "antec", count: 1 },
    { id: 1826, name: "Apacer", slug: "apacer", count: 1 },
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
    { id: 636, name: "ASRock", slug: "asrock", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 2575, name: "ATK", slug: "atk", count: 1 },
    { id: 1907, name: "ATTACK SHARK", slug: "attack-shark", count: 1 },
    { id: 1904, name: "AULA", slug: "aula", count: 1 },
    { id: 555, name: "Bloody", slug: "bloody", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 625, name: "BOOST CORE", slug: "boost-core", count: 1 },
    { id: 627, name: "COLORFUL", slug: "colorful", count: 1 },
    { id: 254, name: "Cooler Master", slug: "cooler-master", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 432, name: "Cougar", slug: "cougar", count: 1 },
    { id: 1868, name: "Crucial", slug: "crucial", count: 1 },
    { id: 255, name: "CrystalX", slug: "crystalx", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 675, name: "Deepcool", slug: "deepcool", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 633, name: "EVGA", slug: "evga", count: 1 },
    { id: 2000, name: "Fantech", slug: "fantech", count: 1 },
    { id: 253, name: "FSP", slug: "fsp", count: 1 },
    { id: 1867, name: "G.SKILL", slug: "g-skill", count: 1 },
    { id: 635, name: "GALAX", slug: "galax", count: 1 },
    { id: 607, name: "Gamdias", slug: "gamdias", count: 1 },
    { id: 433, name: "GameMax", slug: "gamemax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 2582, name: "Glorious", slug: "glorious", count: 1 },
    { id: 2001, name: "GravaStar", slug: "gravastar", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 2212, name: "HyperX", slug: "hyperx", count: 1 },
    { id: 575, name: "HYTE", slug: "hyte", count: 1 },
    { id: 669, name: "ID-Cooling", slug: "id-cooling", count: 1 },
    { id: 630, name: "INNO3D", slug: "inno3d", count: 1 },
    { id: 640, name: "Intel", slug: "intel", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 629, name: "Leadtek", slug: "leadtek", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 476, name: "Lian", slug: "lian", count: 1 },
    { id: 605, name: "Lian-Li", slug: "lian-li", count: 1 },
    { id: 1906, name: "Logitech", slug: "logitech", count: 1 },
    { id: 2121, name: "Madlions", slug: "madlions", count: 1 },
    { id: 626, name: "MAXSUN", slug: "maxsun", count: 1 },
    { id: 2024, name: "Mchose", slug: "mchose", count: 1 },
    { id: 2511, name: "Mchous", slug: "mchous", count: 1 },
    { id: 1908, name: "Meetion", slug: "meetion", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 634, name: "N/A", slug: "n-a", count: 1 },
    { id: 1275, name: "Netac", slug: "netac", count: 1 },
    { id: 637, name: "NVIDIA", slug: "nvidia", count: 1 },
    { id: 601, name: "NZXT", slug: "nzxt", count: 1 },
    { id: 1828, name: "OSCOO", slug: "oscoo", count: 1 },
    { id: 638, name: "Palit", slug: "palit", count: 1 },
    { id: 1827, name: "Patriot", slug: "patriot", count: 1 },
    { id: 2506, name: "Philips", slug: "philips", count: 1 },
    { id: 152, name: "PNY", slug: "pny", count: 1 },
    { id: 1905, name: "Rapoo", slug: "rapoo", count: 1 },
    { id: 2137, name: "Razer", slug: "razer", count: 1 },
    { id: 2239, name: "Redragon", slug: "redragon", count: 1 },
    { id: 514, name: "SAMA", slug: "sama", count: 1 },
    { id: 1269, name: "Samsung", slug: "samsung", count: 1 },
    { id: 1631, name: "SanDisk", slug: "sandisk", count: 1 },
    { id: 631, name: "Sapphire", slug: "sapphire", count: 1 },
    { id: 1509, name: "Seagate", slug: "seagate", count: 1 },
    { id: 556, name: "SilverStone", slug: "silverstone", count: 1 },
    { id: 2166, name: "Skyloong", slug: "skyloong", count: 1 },
    { id: 513, name: "SNOWMAN", slug: "snowman", count: 1 },
    { id: 475, name: "Sonic", slug: "sonic", count: 1 },
    { id: 2061, name: "SteelSeries", slug: "steelseries", count: 1 },
    { id: 820, name: "Super Flower", slug: "super-flower", count: 1 },
    { id: 1266, name: "TeamGroup", slug: "teamgroup", count: 1 },
    { id: 516, name: "Thermalright", slug: "thermalright", count: 1 },
    { id: 472, name: "Thermaltake", slug: "thermaltake", count: 1 },
    { id: 1999, name: "Thinkway", slug: "thinkway", count: 1 },
    { id: 206, name: "Thunder", slug: "thunder", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 2447, name: "UGREEN", slug: "ugreen", count: 1 },
    { id: 1242, name: "WD", slug: "wd", count: 1 },
    { id: 632, name: "XFX", slug: "xfx", count: 1 },
    { id: 606, name: "Xigmatek", slug: "xigmatek", count: 1 },
    { id: 2062, name: "XINMENG", slug: "xinmeng", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
    { id: 145, name: "ZOTAC", slug: "zotac", count: 1 },
  ],
  "desktop-ram": [
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 1867, name: "G.SKILL", slug: "g-skill", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1266, name: "TeamGroup", slug: "teamgroup", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "external-portable-drives": [
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1269, name: "Samsung", slug: "samsung", count: 1 },
    { id: 1631, name: "SanDisk", slug: "sandisk", count: 1 },
    { id: 1509, name: "Seagate", slug: "seagate", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 1242, name: "WD", slug: "wd", count: 1 },
  ],
  "gaming-keyboards": [
    { id: 2002, name: "A4Tech", slug: "a4tech", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 1907, name: "ATTACK SHARK", slug: "attack-shark", count: 1 },
    { id: 1904, name: "AULA", slug: "aula", count: 1 },
    { id: 555, name: "Bloody", slug: "bloody", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 2000, name: "Fantech", slug: "fantech", count: 1 },
    { id: 2001, name: "GravaStar", slug: "gravastar", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 2212, name: "HyperX", slug: "hyperx", count: 1 },
    { id: 575, name: "HYTE", slug: "hyte", count: 1 },
    { id: 1906, name: "Logitech", slug: "logitech", count: 1 },
    { id: 2121, name: "Madlions", slug: "madlions", count: 1 },
    { id: 2024, name: "Mchose", slug: "mchose", count: 1 },
    { id: 1908, name: "Meetion", slug: "meetion", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 1905, name: "Rapoo", slug: "rapoo", count: 1 },
    { id: 2137, name: "Razer", slug: "razer", count: 1 },
    { id: 2239, name: "Redragon", slug: "redragon", count: 1 },
    { id: 2166, name: "Skyloong", slug: "skyloong", count: 1 },
    { id: 2061, name: "SteelSeries", slug: "steelseries", count: 1 },
    { id: 1999, name: "Thinkway", slug: "thinkway", count: 1 },
    { id: 2062, name: "XINMENG", slug: "xinmeng", count: 1 },
  ],
  "gaming-mouse": [
    { id: 2002, name: "A4Tech", slug: "a4tech", count: 1 },
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 2575, name: "ATK", slug: "atk", count: 1 },
    { id: 1907, name: "ATTACK SHARK", slug: "attack-shark", count: 1 },
    { id: 1904, name: "AULA", slug: "aula", count: 1 },
    { id: 555, name: "Bloody", slug: "bloody", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 255, name: "CrystalX", slug: "crystalx", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 2000, name: "Fantech", slug: "fantech", count: 1 },
    { id: 2582, name: "Glorious", slug: "glorious", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 2212, name: "HyperX", slug: "hyperx", count: 1 },
    { id: 1906, name: "Logitech", slug: "logitech", count: 1 },
    { id: 2024, name: "Mchose", slug: "mchose", count: 1 },
    { id: 2511, name: "Mchous", slug: "mchous", count: 1 },
    { id: 1908, name: "Meetion", slug: "meetion", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 2506, name: "Philips", slug: "philips", count: 1 },
    { id: 1905, name: "Rapoo", slug: "rapoo", count: 1 },
    { id: 2137, name: "Razer", slug: "razer", count: 1 },
    { id: 2239, name: "Redragon", slug: "redragon", count: 1 },
    { id: 2061, name: "SteelSeries", slug: "steelseries", count: 1 },
    { id: 2447, name: "UGREEN", slug: "ugreen", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "graphics-cards": [
    { id: 636, name: "ASRock", slug: "asrock", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 627, name: "COLORFUL", slug: "colorful", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 633, name: "EVGA", slug: "evga", count: 1 },
    { id: 635, name: "GALAX", slug: "galax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 630, name: "INNO3D", slug: "inno3d", count: 1 },
    { id: 629, name: "Leadtek", slug: "leadtek", count: 1 },
    { id: 626, name: "MAXSUN", slug: "maxsun", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 634, name: "N/A", slug: "n-a", count: 1 },
    { id: 637, name: "NVIDIA", slug: "nvidia", count: 1 },
    { id: 638, name: "Palit", slug: "palit", count: 1 },
    { id: 152, name: "PNY", slug: "pny", count: 1 },
    { id: 631, name: "Sapphire", slug: "sapphire", count: 1 },
    { id: 632, name: "XFX", slug: "xfx", count: 1 },
    { id: 145, name: "ZOTAC", slug: "zotac", count: 1 },
  ],
  "keyboard-mouse-combos-set": [
    { id: 2002, name: "A4Tech", slug: "a4tech", count: 1 },
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 555, name: "Bloody", slug: "bloody", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 1906, name: "Logitech", slug: "logitech", count: 1 },
    { id: 1908, name: "Meetion", slug: "meetion", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 1905, name: "Rapoo", slug: "rapoo", count: 1 },
    { id: 514, name: "SAMA", slug: "sama", count: 1 },
  ],
  "laptop-ram": [
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 1826, name: "Apacer", slug: "apacer", count: 1 },
    { id: 1868, name: "Crucial", slug: "crucial", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1828, name: "OSCOO", slug: "oscoo", count: 1 },
    { id: 1827, name: "Patriot", slug: "patriot", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
  ],
  "laptops": [
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 2627, name: "Dell", slug: "dell", count: 1 },
    { id: 3694, name: "Fujitsu", slug: "fujitsu", count: 1 },
    { id: 3539, name: "Gateway", slug: "gateway", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 1508, name: "Lenovo", slug: "lenovo", count: 1 },
    { id: 2632, name: "Microsoft", slug: "microsoft", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 2137, name: "Razer", slug: "razer", count: 1 },
    { id: 1269, name: "Samsung", slug: "samsung", count: 1 },
    { id: 4677, name: "Toshiba", slug: "toshiba", count: 1 },
  ],
  "latest-arrival": [
    { id: 641, name: "AMD", slug: "amd", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 432, name: "Cougar", slug: "cougar", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 575, name: "HYTE", slug: "hyte", count: 1 },
    { id: 640, name: "Intel", slug: "intel", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 601, name: "NZXT", slug: "nzxt", count: 1 },
    { id: 606, name: "Xigmatek", slug: "xigmatek", count: 1 },
    { id: 145, name: "ZOTAC", slug: "zotac", count: 1 },
  ],
  "macbook": [
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
  ],
  "motherboards": [
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 625, name: "BOOST CORE", slug: "boost-core", count: 1 },
    { id: 627, name: "COLORFUL", slug: "colorful", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 626, name: "MAXSUN", slug: "maxsun", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
  ],
  "nvme-enclosure": [
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
  ],
  "nvme-ssd": [
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1275, name: "Netac", slug: "netac", count: 1 },
    { id: 1269, name: "Samsung", slug: "samsung", count: 1 },
    { id: 1266, name: "TeamGroup", slug: "teamgroup", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 1242, name: "WD", slug: "wd", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "office-keyboards": [
    { id: 2002, name: "A4Tech", slug: "a4tech", count: 1 },
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 2479, name: "Apple", slug: "apple", count: 1 },
    { id: 1907, name: "ATTACK SHARK", slug: "attack-shark", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
    { id: 1906, name: "Logitech", slug: "logitech", count: 1 },
    { id: 1908, name: "Meetion", slug: "meetion", count: 1 },
    { id: 1905, name: "Rapoo", slug: "rapoo", count: 1 },
    { id: 2137, name: "Razer", slug: "razer", count: 1 },
  ],
  "on-sale": [
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 433, name: "GameMax", slug: "gamemax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 631, name: "Sapphire", slug: "sapphire", count: 1 },
    { id: 475, name: "Sonic", slug: "sonic", count: 1 },
    { id: 516, name: "Thermalright", slug: "thermalright", count: 1 },
  ],
  "pc-cases": [
    { id: 515, name: "1st", slug: "1st", count: 1 },
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 555, name: "Bloody", slug: "bloody", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 254, name: "Cooler Master", slug: "cooler-master", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 432, name: "Cougar", slug: "cougar", count: 1 },
    { id: 255, name: "CrystalX", slug: "crystalx", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 253, name: "FSP", slug: "fsp", count: 1 },
    { id: 607, name: "Gamdias", slug: "gamdias", count: 1 },
    { id: 433, name: "GameMax", slug: "gamemax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 575, name: "HYTE", slug: "hyte", count: 1 },
    { id: 476, name: "Lian", slug: "lian", count: 1 },
    { id: 605, name: "Lian-Li", slug: "lian-li", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 601, name: "NZXT", slug: "nzxt", count: 1 },
    { id: 514, name: "SAMA", slug: "sama", count: 1 },
    { id: 556, name: "SilverStone", slug: "silverstone", count: 1 },
    { id: 513, name: "SNOWMAN", slug: "snowman", count: 1 },
    { id: 475, name: "Sonic", slug: "sonic", count: 1 },
    { id: 516, name: "Thermalright", slug: "thermalright", count: 1 },
    { id: 472, name: "Thermaltake", slug: "thermaltake", count: 1 },
    { id: 206, name: "Thunder", slug: "thunder", count: 1 },
    { id: 606, name: "Xigmatek", slug: "xigmatek", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "pc-cooling-systems": [
    { id: 684, name: "1st Player", slug: "1st-player", count: 1 },
    { id: 681, name: "AeroCool", slug: "aerocool", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 254, name: "Cooler Master", slug: "cooler-master", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 432, name: "Cougar", slug: "cougar", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 675, name: "Deepcool", slug: "deepcool", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 433, name: "GameMax", slug: "gamemax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 669, name: "ID-Cooling", slug: "id-cooling", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 514, name: "SAMA", slug: "sama", count: 1 },
    { id: 556, name: "SilverStone", slug: "silverstone", count: 1 },
    { id: 513, name: "SNOWMAN", slug: "snowman", count: 1 },
    { id: 516, name: "Thermalright", slug: "thermalright", count: 1 },
    { id: 472, name: "Thermaltake", slug: "thermaltake", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "power-supplies": [
    { id: 684, name: "1st Player", slug: "1st-player", count: 1 },
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 982, name: "Aigo", slug: "aigo", count: 1 },
    { id: 1141, name: "Antec", slug: "antec", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 545, name: "Boost", slug: "boost", count: 1 },
    { id: 254, name: "Cooler Master", slug: "cooler-master", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 432, name: "Cougar", slug: "cougar", count: 1 },
    { id: 544, name: "DarkFlash", slug: "darkflash", count: 1 },
    { id: 675, name: "Deepcool", slug: "deepcool", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 253, name: "FSP", slug: "fsp", count: 1 },
    { id: 433, name: "GameMax", slug: "gamemax", count: 1 },
    { id: 148, name: "GIGABYTE", slug: "gigabyte", count: 1 },
    { id: 605, name: "Lian-Li", slug: "lian-li", count: 1 },
    { id: 191, name: "MSI", slug: "msi", count: 1 },
    { id: 556, name: "SilverStone", slug: "silverstone", count: 1 },
    { id: 820, name: "Super Flower", slug: "super-flower", count: 1 },
    { id: 516, name: "Thermalright", slug: "thermalright", count: 1 },
    { id: 472, name: "Thermaltake", slug: "thermaltake", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "printers-and-scanners": [
    { id: 250, name: "EPSON", slug: "epson", count: 1 },
    { id: 251, name: "HP", slug: "hp", count: 1 },
  ],
  "processors": [
    { id: 641, name: "AMD", slug: "amd", count: 1 },
    { id: 640, name: "Intel", slug: "intel", count: 1 },
  ],
  "ram": [
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 1826, name: "Apacer", slug: "apacer", count: 1 },
    { id: 216, name: "Corsair", slug: "corsair", count: 1 },
    { id: 1868, name: "Crucial", slug: "crucial", count: 1 },
    { id: 1867, name: "G.SKILL", slug: "g-skill", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1828, name: "OSCOO", slug: "oscoo", count: 1 },
    { id: 1827, name: "Patriot", slug: "patriot", count: 1 },
    { id: 1266, name: "TeamGroup", slug: "teamgroup", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
  "storage": [
    { id: 474, name: "Acer", slug: "acer", count: 1 },
    { id: 1253, name: "ADATA", slug: "adata", count: 1 },
    { id: 1248, name: "Amaze", slug: "amaze", count: 1 },
    { id: 118, name: "ASUS", slug: "asus", count: 1 },
    { id: 116, name: "EASE", slug: "ease", count: 1 },
    { id: 1272, name: "HikSemi", slug: "hiksemi", count: 1 },
    { id: 1260, name: "Kingston", slug: "kingston", count: 1 },
    { id: 1262, name: "Lexar", slug: "lexar", count: 1 },
    { id: 1275, name: "Netac", slug: "netac", count: 1 },
    { id: 1269, name: "Samsung", slug: "samsung", count: 1 },
    { id: 1631, name: "SanDisk", slug: "sandisk", count: 1 },
    { id: 1509, name: "Seagate", slug: "seagate", count: 1 },
    { id: 1266, name: "TeamGroup", slug: "teamgroup", count: 1 },
    { id: 1256, name: "Transcend", slug: "transcend", count: 1 },
    { id: 1242, name: "WD", slug: "wd", count: 1 },
    { id: 473, name: "XPG", slug: "xpg", count: 1 },
  ],
};
